add_newline = false

[battery]
format = "[$symbol $percentage]($style) "
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡ï¸"

[[battery.display]]
threshold = 25
style = "bold #ff9900"

[character]
success_symbol = "[â†³](bold green)"
error_symbol = "[â†³](bold red)"

[status]
disabled = false
symbol = "âœ–"
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '

[git_branch]
symbol = "ï˜ "

[git_status]
disabled = true
